name: Oss Service Integration Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: [ '17','21' ]
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    env:
      SERVER_PORT_NO: 8081
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B -P+it  package -Djava.version=${{ matrix.java }} --file pom.xml
      - name: Run AllInOne Application
        uses: JarvusInnovations/background-action@v1.0.7
        with:
          working-directory: oss-server
          wait-for: 2m
          tail: true
          run: java -jar target/oss-server-fat.jar --spring.profiles.active=oss-dev &
          wait-on: http-get://localhost:${{ env.SERVER_PORT_NO }}/actuator/health
      - name: Download ijhttp tools
        run: |-
          #curl -f -L -o ijhttp.zip "https://jb.gg/ijhttp/latest"
          #unzip ijhttp.zip
          #./ijhttp/ijhttp --version
          docker pull jetbrains/intellij-http-client:233.15026.9
          docker tag  jetbrains/intellij-http-client:233.15026.9 ijhttp
      - name: Execute HTTP requests
        run: |-
          #./ijhttp/ijhttp oss-server/src/test/http/test.http oss-server/src/test/http/chunked.http
          docker run --rm -v ./oss-server:/workdir --add-host host.docker.internal:host-gateway ijhttp -D \
                src/test/http/chunked.http src/test/http/test.http
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ "build" ]
    runs-on: ubuntu-22.04
    env:
      MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      GPG_SECURITY_PWD: ${{ secrets.GPG_SECURITY_PWD }}
    steps:
      - name: Install gpg secret key
        run: |-
          # Install gpg secret key
          cat <(echo -e "${{ secrets.GPG_SECURITY_KEY }}") | gpg --batch --import
          # Verify gpg secret key
          gpg --list-secret-keys --keyid-format LONG
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - name: Set up maven settings
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "ossrh",
              "username": "${{ secrets.OSSRH_USERNAME }}",
              "password": "${{ secrets.OSSRH_TOKEN }}"
            }]
      - name: Deploy to OSSRH
        run: mvn -P it,deploy -Djava.version=17 -DskipTests=true clean deploy
