name: Oss Service Integration Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: it
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: [ '17','21' ]
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    env:
      SERVER_PORT_NO: 8081
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B -P+it  package -Djava.version=${{ matrix.java }} --file pom.xml
      - name: Run AllInOne Application
        uses: JarvusInnovations/background-action@v1
        with:
          working-directory: oss-service
          wait-for: 2m
          tail: true
          run: java -jar target/oss-service-fat.jar &
          wait-on: http-get://localhost:${{ env.SERVER_PORT_NO }}/actuator/health
      - name: Download ijhttp tools
        run: |-
          curl -f -L -o ijhttp.zip "https://jb.gg/ijhttp/latest"
          unzip ijhttp.zip
          ./ijhttp/ijhttp --version
      - name: Execute HTTP requests
        run: ./ijhttp/ijhttp oss-service/src/test/http/test.http oss-service/src/test/http/chunked.http
